.PHONY: test

test:
	@echo "Running basic example..."
	@cd basic && go run .

	@echo "\nRunning bindlogger example..."
	@cd bindlogger && go run .

	@echo "\nRunning dynamiconstructor example..."
	@cd dynamiconstructor && go run .

	@echo "\nRunning guessing_types example..."
	@cd guessing_types && go run .
