.PHONY: test

test:
	@echo "Running basic example..."
	@go -C basic run .

	@echo "\nRunning bindlogger example..."
	@go -C bindlogger run .

	@echo "\nRunning dynamiconstructor example..."
	@go -C dynamiconstructor run .

	@echo "\nRunning guessing_types example..."
	@go -C guessing_types run .
